AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo CloudFormation

Resources:
  EmminSanko:
    Type: AWS::S3::Bucket

  EmminJono:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 30
