AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo CloudFormation

Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t2.micro
    Description: Only t3.micro or t2.micro allowed.

  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-kernel-5.10-hvm-x86_64-gp2"

Resources:
  EmminSanko:
    Type: "AWS::S3::Bucket"

  EmminJono:
    Type: "AWS::SQS::Queue"
    Properties:
      VisibilityTimeout: 30

  SecurityGroupEC2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 instances.
      GroupName: emmin-ec2-sg
      SecurityGroupIngress:
        - SourceSecurityGroupId: "sg-0f4394f4d4c011281"
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
      VpcId: "vpc-08d981244c306404d"

  SecurityGroupALB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Application Load Balancer.
      GroupName: emmin-alb-sg
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
      VpcId: "vpc-08d981244c306404d"

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: "EmminASG"
      AvailabilityZones:
        - "eu-north-1a"
        - "eu-north-1b"
        - "eu-north-1c"
      LaunchConfigurationName: !Ref LaunchConfiguration
      MaxSize: 3
      MinSize: 1
      TargetGroupARNs:
        - !Ref LBTargetGroup
      VPCZoneIdentifier:
        - "subnet-04014b79f5d358982"
        - "subnet-03cb17b85212448ad"
        - "subnet-023c8647d04b76ab8"

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceTypeParameter
      LaunchConfigurationName: "EmminLC"
      SecurityGroups:
        - !Ref SecurityGroupEC2
      UserData:
        Fn::Base64:
          Fn::Join:
            - "\n"
            - - "#!/bin/bash"
              - "amazon-linux-extras install epel"
              - "amazon-linux-extras install nginx1"
              - "systemctl start nginx"

  EmminALBV2:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: EmminALBV2
      Scheme: internet-facing
      SecurityGroups:
        - !Ref SecurityGroupALB
      Subnets:
        - "subnet-04014b79f5d358982"
        - "subnet-03cb17b85212448ad"
        - "subnet-023c8647d04b76ab8"

  LBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref LBTargetGroup
          Type: "forward"
      LoadBalancerArn: "arn:aws:elasticloadbalancing:eu-north-1:235920682125:loadbalancer/app/EmminALBV2/930757e78afe51b3"
      Port: 80
      Protocol: "HTTP"

  LBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: "HTTP"
      VpcId: "vpc-08d981244c306404d"

Outputs:
  ALBOutput:
    Description: DNS of ALB
    Value: !GetAtt EmminALBV2.DNSName
