AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo CloudFormation

Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t2.micro
    Description: Only t3.micro or t2.micro allowed.

  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-kernel-5.10-hvm-x86_64-gp2"

Resources:
  EmminSanko:
    Type: "AWS::S3::Bucket"

  EmminJono:
    Type: "AWS::SQS::Queue"
    Properties:
      VisibilityTimeout: 30

  SecurityGroupEC2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 instances.
      GroupName: emmin-ec2-sg
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
      VpcId: "vpc-08d981244c306404d"

  SecurityGroupALB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Application Load Balancer.
      GroupName: emmin-alb-sg
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
      VpcId: "vpc-08d981244c306404d"

  EmminEC22:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType:
        Ref: InstanceTypeParameter
      AvailabilityZone: eu-north-1a
      ImageId: !Ref LatestAmiId
      SecurityGroupIds:
        - !GetAtt SecurityGroupEC2.GroupId
      Tags:
        - Key: Name
          Value: EmminEC2-2

  EmminALB:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Listeners:
        - LoadBalancerPort: "80"
          InstancePort: "80"
          Protocol: HTTP
      Scheme: internet-facing
      Subnets:
        - "subnet-04014b79f5d358982"
        - "subnet-03cb17b85212448ad"
        - "subnet-023c8647d04b76ab8"
      SecurityGroups:
        - !Ref SecurityGroupALB
      Tags:
        - Key: Name
          Value: EmminALB

Outputs:
  ALBOutput:
    Description: DNS of ALB
    Value: !GetAtt EmminALB.DNSName
